### PR TITLE
Peter parslow patch 1

### PR DESCRIPTION
**Pull request by PeterParslow**
Change the "return to home page" links to point to the new "introduction" text, which partly resolves https://github.com/agiorguk/gemini/issues/24 and https://github.com/agiorguk/gemini/issues/31

The other action would be to get AGI to redirect to the new page rather than the current "home page".

Remove the Word & HTML files from 'pending' that relate to fixing this issue in the old publication route.

### CODE REVIEW

**Comment by PeterParslow** [comment]
Also deleted the "pending" files (& folder) because all those changes have been implemented during migration.

**Review by archaeogeek — APPROVED** [review]

**Comment by archaeogeek** [comment]
Reviewed and approved by @archaeogeek

**Comment by PeterParslow** [comment]
Jo, I'm a bit confused by this message:

"Closed with unmerged commits" - I will try to find what commits I made to the PeterParslow-patch 1 branch that somehow didn't  get merged.
I also thought I'd asked for it to be merged into "dev" as per agreed process, but here is says its merged into "main". The "return to home page" links haven't changed in the "main" branch. But neither can I see the changes in the dev branch.

Have you closed it without merging this PR at all, @archaeogeek ?

**Comment by archaeogeek** [comment]
Can you try editing this PR (edit button at the top, by the title) and changing the `base` from `main` to `dev`?

**Comment by PeterParslow** [comment]
> Can you try editing this PR (edit button at the top, by the title) and changing the `base` from `main` to `dev`?

Done; it gave me a warning, but seemed OK to change.

**Comment by PeterParslow** [comment]
> @PeterParslow I had assumed that it was because you had a second PR as well, but I'm not sure, so I will reopen and have a dig.

I think Patch 1 covered the issues that had already been sent to AGI. Patch 2 includes the ones that were in the "pending release" column, but where the HTML hadn't been sent to AGI.

**Pull request merged**
